// <auto-generated />
using HangHoaManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace baikiemtra.Migrations
{
    [DbContext(typeof(GoodDbContext))]
    partial class GoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HangHoaManagement.Models.hang_hoa", b =>
                {
                    b.Property<string>("ma_hanghoa")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("ma_hanghoa");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("so_luong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<string>("ten_hanghoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_hanghoa");

                    b.HasKey("ma_hanghoa");

                    b.ToTable("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
